name: Scrape Vinted every 30 min

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps firefox
      - name: Run scraper
        env:
          PROFILE_URL: ${{ secrets.PROFILE_URL }}
          MAX_PAGES: ${{ secrets.MAX_PAGES }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python cron_scrape.py
